# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         CGI-Application-Gallery
version:      1.04
version_from: lib/CGI/Application/Gallery.pm
installdirs:  site
requires:
    Carp:                          0
    CGI::Application:              0
    CGI::Application::Plugin::AutoRunmode: 0
    CGI::Application::Plugin::Feedback: 0
    CGI::Application::Plugin::Forward: 0
    CGI::Application::Plugin::Session: 0
    CGI::Application::Plugin::Stream: 0
    CGI::Application::Plugin::Thumbnail: 0
    CGI::Application::Plugin::TmplInnerOuter: 0
    Data::Page:                    0
    File::PathInfo::Ext:           1
    LEOCHARRE::DEBUG:              0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
